apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: pce-server-delay
  namespace: default
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: pce-server
  delay:
    latency: '2500ms'
    jitter: '100ms'
  direction: to
  duration: '2h'
